"""fix genres tablename

Revision ID: 6bee64d58278
Revises: 81c78e8e9bca
Create Date: 2023-11-09 13:03:25.838491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bee64d58278'
down_revision = '81c78e8e9bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('designer_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['designers.id'], name=op.f('fk_games_designer_id_designers')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_games_genre_id_genres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), nullable=False),
    sa.Column('players', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.INTEGER(), nullable=False),
    sa.Column('designer_id', sa.INTEGER(), nullable=False),
    sa.Column('genre_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['designers.id'], name='fk_game_designer_id_designers'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='fk_game_genre_id_genres'),
    sa.PrimaryKeyConstraint('id', name='pk_game')
    )
    op.drop_table('games')
    # ### end Alembic commands ###
