"""added unique to game title

Revision ID: 77647c806b4a
Revises: 2ac1619a423c
Create Date: 2023-11-22 09:15:01.771291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77647c806b4a'
down_revision = '2ac1619a423c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_designers_name', type_='unique')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_games_title'), ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_games_title'), type_='unique')

    with op.batch_alter_table('designers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_designers_name', ['name'])

    # ### end Alembic commands ###
